# This workflow will deploy a MuleSoft project

name: Deploy Mulesoft

on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - uses: actions/download-artifact@master
      with:
        name: artifacts
    
    - name: Deploy to Sandbox
      env:
        USERNAME: ${{ secrets.anypoint_cicd_username }}
        PASSWORD: ${{ secrets.anypoint_cicd_password }}
        DECRYPTION_KEY: ${{ secrets.secretkey }}
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy \
         -Dmule.artifact=$artifactName \
         -Danypoint.username="$USERNAME" \
         -Danypoint.password="$PASSWORD" \
         -Denv=Sandbox \
         -Ddecryption.key="$DECRYPTION_KEY" \
         -DskipTests